# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 826)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777214, 16777215))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.encryption_panel = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encryption_panel.sizePolicy().hasHeightForWidth())
        self.encryption_panel.setSizePolicy(sizePolicy)
        self.encryption_panel.setObjectName("encryption_panel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.encryption_panel)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.enc_M_panel = QtWidgets.QGroupBox(self.encryption_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enc_M_panel.sizePolicy().hasHeightForWidth())
        self.enc_M_panel.setSizePolicy(sizePolicy)
        self.enc_M_panel.setObjectName("enc_M_panel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.enc_M_panel)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.enc_M_text = QtWidgets.QTextEdit(self.enc_M_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enc_M_text.sizePolicy().hasHeightForWidth())
        self.enc_M_text.setSizePolicy(sizePolicy)
        self.enc_M_text.setObjectName("enc_M_text")
        self.verticalLayout_4.addWidget(self.enc_M_text)
        self.encryption_button = QtWidgets.QPushButton(self.enc_M_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encryption_button.sizePolicy().hasHeightForWidth())
        self.encryption_button.setSizePolicy(sizePolicy)
        self.encryption_button.setObjectName("encryption_button")
        self.verticalLayout_4.addWidget(self.encryption_button)
        self.gridLayout_2.addWidget(self.enc_M_panel, 0, 0, 1, 1)
        self.enc_K_panel = QtWidgets.QGroupBox(self.encryption_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enc_K_panel.sizePolicy().hasHeightForWidth())
        self.enc_K_panel.setSizePolicy(sizePolicy)
        self.enc_K_panel.setObjectName("enc_K_panel")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.enc_K_panel)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.enc_K_text = QtWidgets.QTextBrowser(self.enc_K_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enc_K_text.sizePolicy().hasHeightForWidth())
        self.enc_K_text.setSizePolicy(sizePolicy)
        self.enc_K_text.setObjectName("enc_K_text")
        self.horizontalLayout_4.addWidget(self.enc_K_text)
        self.gridLayout_2.addWidget(self.enc_K_panel, 1, 0, 1, 1)
        self.enc_C_panel = QtWidgets.QGroupBox(self.encryption_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enc_C_panel.sizePolicy().hasHeightForWidth())
        self.enc_C_panel.setSizePolicy(sizePolicy)
        self.enc_C_panel.setObjectName("enc_C_panel")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.enc_C_panel)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.enc_C_text = QtWidgets.QTextBrowser(self.enc_C_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enc_C_text.sizePolicy().hasHeightForWidth())
        self.enc_C_text.setSizePolicy(sizePolicy)
        self.enc_C_text.setObjectName("enc_C_text")
        self.horizontalLayout_5.addWidget(self.enc_C_text)
        self.gridLayout_2.addWidget(self.enc_C_panel, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.encryption_panel, 0, 0, 1, 1)
        self.decryption_panel = QtWidgets.QGroupBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decryption_panel.sizePolicy().hasHeightForWidth())
        self.decryption_panel.setSizePolicy(sizePolicy)
        self.decryption_panel.setObjectName("decryption_panel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.decryption_panel)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dec_C_panel = QtWidgets.QGroupBox(self.decryption_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_C_panel.sizePolicy().hasHeightForWidth())
        self.dec_C_panel.setSizePolicy(sizePolicy)
        self.dec_C_panel.setObjectName("dec_C_panel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dec_C_panel)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dec_C_text = QtWidgets.QTextEdit(self.dec_C_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_C_text.sizePolicy().hasHeightForWidth())
        self.dec_C_text.setSizePolicy(sizePolicy)
        self.dec_C_text.setObjectName("dec_C_text")
        self.verticalLayout_5.addWidget(self.dec_C_text)
        self.decrypt_button = QtWidgets.QPushButton(self.dec_C_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decrypt_button.sizePolicy().hasHeightForWidth())
        self.decrypt_button.setSizePolicy(sizePolicy)
        self.decrypt_button.setObjectName("decrypt_button")
        self.verticalLayout_5.addWidget(self.decrypt_button)
        self.gridLayout_3.addWidget(self.dec_C_panel, 0, 0, 1, 1)
        self.dec_K_panel = QtWidgets.QGroupBox(self.decryption_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_K_panel.sizePolicy().hasHeightForWidth())
        self.dec_K_panel.setSizePolicy(sizePolicy)
        self.dec_K_panel.setObjectName("dec_K_panel")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dec_K_panel)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dec_K_text = QtWidgets.QTextEdit(self.dec_K_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_K_text.sizePolicy().hasHeightForWidth())
        self.dec_K_text.setSizePolicy(sizePolicy)
        self.dec_K_text.setObjectName("dec_K_text")
        self.horizontalLayout_6.addWidget(self.dec_K_text)
        self.gridLayout_3.addWidget(self.dec_K_panel, 1, 0, 1, 1)
        self.dec_M_panel = QtWidgets.QGroupBox(self.decryption_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_M_panel.sizePolicy().hasHeightForWidth())
        self.dec_M_panel.setSizePolicy(sizePolicy)
        self.dec_M_panel.setObjectName("dec_M_panel")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.dec_M_panel)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dec_M_text = QtWidgets.QTextBrowser(self.dec_M_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_M_text.sizePolicy().hasHeightForWidth())
        self.dec_M_text.setSizePolicy(sizePolicy)
        self.dec_M_text.setObjectName("dec_M_text")
        self.horizontalLayout_7.addWidget(self.dec_M_text)
        self.gridLayout_3.addWidget(self.dec_M_panel, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.decryption_panel, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.central_widget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 672, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DNA Cipher"))
        self.encryption_panel.setTitle(_translate("MainWindow", "Encryption"))
        self.enc_M_panel.setTitle(_translate("MainWindow", "Secret Message M"))
        self.encryption_button.setText(_translate("MainWindow", "Encrypt"))
        self.enc_K_panel.setTitle(_translate("MainWindow", "Secret Key K"))
        self.enc_C_panel.setTitle(_translate("MainWindow", "Encrypted Message C"))
        self.decryption_panel.setTitle(_translate("MainWindow", "Decryption"))
        self.dec_C_panel.setTitle(_translate("MainWindow", "Encrypted Message C"))
        self.decrypt_button.setText(_translate("MainWindow", "Decrypt"))
        self.dec_K_panel.setTitle(_translate("MainWindow", "Secret Key K"))
        self.dec_M_panel.setTitle(_translate("MainWindow", "Decrypted Message M"))

